=== nsip/specgen_input/sifSpecificationGeneratorConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by Vince Paredes (SIF Association) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sifassociation.org/sifSpecificationGenerator/1.0" targetNamespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="sifSpecificationGeneratorConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="globalSettings">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="inputDocument" type="xs:normalizedString"/>
							<xs:element name="sifNamespace" type="xs:normalizedString"/>
							<xs:element name="localizationCode" type="xs:normalizedString"/>
							<xs:element name="schemaVersion" type="xs:normalizedString"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="htmlDocuments">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="htmlDocument" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="singleDocument" type="xs:boolean"/>
										<xs:element name="rootDocumentFileName" type="xs:normalizedString"/>
										<xs:element name="rootTitle" type="xs:normalizedString"/>
										<xs:element name="documentType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="DataModel"/>
													<xs:enumeration value="Infrastructure"/>
													<xs:enumeration value="Combined"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="webServiceDocuments" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="webServiceDocument" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="singleDocument" type="xs:boolean"/>
										<xs:element name="rootDocumentFileName" type="xs:normalizedString"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="xsdDocuments">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="xsdDocument" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="xsdTitle" type="xs:normalizedString"/>
										<xs:element name="diagram" type="xs:boolean"/>
										<xs:element name="isDataModelXsd" type="xs:boolean"/>
										<xs:element name="singleSchema" type="xs:boolean"/>
										<xs:element name="annotate" type="xs:boolean"/>
										<xs:element name="listWithKeyConstraints" type="xs:boolean"/>
										<xs:element name="isSifMessage2Xsd" type="xs:boolean"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nsip/specgen_input/SIF.Config_DataModel.xml
<?xml version="1.0" encoding="utf-8"?>
<sifSpecificationGeneratorConfig xmlns="http://www.sifassociation.org/sifSpecificationGenerator/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sifassociation.org/sifSpecificationGenerator/1.0  sifSpecificationGeneratorConfig.xsd">
	
	<globalSettings>
		<inputDocument>SIF_DataModel.xml</inputDocument>
		<sifNamespace>http://www.sifinfo.org/au/infrastructure/2.x</sifNamespace>
		<localizationCode>au</localizationCode>
	</globalSettings>
	
	<htmlDocuments>
	
		<!-- document 1: many documents-->
		<htmlDocument>
			<singleDocument>false</singleDocument>
			<rootDocumentFileName>index.html</rootDocumentFileName>
			<rootTitle>SIF Implementation Specification (Australia) 1.4</rootTitle>
			<documentType>DataModel</documentType>
		</htmlDocument>
		
		<!-- document 2: Single document-->
		<htmlDocument>
			<singleDocument>true</singleDocument>
			<rootDocumentFileName>ImplementationSpecification.html</rootDocumentFileName>
			<rootTitle>SIF Implementation Specification (Australia) 1.4</rootTitle>
			<documentType>DataModel</documentType>
		</htmlDocument>
		
	</htmlDocuments>
	
	
	<webServiceDocuments>
   
  </webServiceDocuments>
  
  
	<xsdDocuments>
	
		<xsdDocument>
			<xsdTitle>SIF_MessageNoIncludes</xsdTitle>
			<diagram>true</diagram>
			<isDataModelXsd>false</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>true</singleSchema>
			<annotate>false</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>SIF_MessageNoIncludesAnnotated</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>false</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>true</singleSchema>
			<annotate>true</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>SIF_Message</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>false</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>false</singleSchema>
			<annotate>false</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>SIF_MessageAnnotated</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>false</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>false</singleSchema>
			<annotate>true</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>DataModelNoIncludes</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>true</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>true</singleSchema>
			<annotate>false</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>DataModelNoIncludesAnnotated</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>true</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>true</singleSchema>
			<annotate>true</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>DataModel</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>true</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>false</singleSchema>
			<annotate>false</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		
		<xsdDocument>
			<xsdTitle>DataModelAnnotated</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>true</isDataModelXsd>
			<isServiceBodyXsd>false</isServiceBodyXsd>
			<singleSchema>false</singleSchema>
			<annotate>true</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>
		

		<xsdDocument>
			<xsdTitle>ServiceBodyDefinitions</xsdTitle>
			<diagram>false</diagram>
			<isDataModelXsd>false</isDataModelXsd>
			<isServiceBodyXsd>true</isServiceBodyXsd>
			<singleSchema>false</singleSchema>
			<annotate>true</annotate>
			<listWithKeyConstraints>false</listWithKeyConstraints>
			<isSifMessage2Xsd>false</isSifMessage2Xsd>
		</xsdDocument>  
		
	</xsdDocuments>
</sifSpecificationGeneratorConfig>
